In [13]:
import pandas as pd
PAM = pd.read_csv('/Users/yutonomy/Dropbox/Columbia SIPA/24FALL/Computing in Context/Project1/Pregnancy-Associated_Mortality_20241108.csv')
PAM

,Year,Related,Underlying_cause,Race/ethnicity,Borough,Deaths
0,2016,All,All,All,Bronx,5.0
1,2016,All,All,All,Brooklyn,12.0
2,2016,All,All,All,Manhattan,4.0
3,2016,All,All,All,Queens,8.0
4,2016,All,All,All,Staten Island,4.0
...,...,...,...,...,...,...
231,2021,Unable to Determine,Mental Health Conditions (Overdose related to ...,All,All,6.0
232,2021,Unable to Determine,Other,All,All,3.0
233,2021,Unable to Determine,Cancer,All,All,2.0
234,2021,Unable to Determine,Infection/Sepsis,All,All,2.0
235,2021,Unable to Determine,Unknown COD,All,All,2.0

In [25]:
mean_value = PAM['Deaths'].mean()
median_value = PAM['Deaths'].median()
mode_value = PAM['Deaths'].mode()[0]

mean_value, median_value, mode_value

(5.017021276595744, 3.0, 1.0)

In [34]:
import csv
file_path = '/Users/yutonomy/Dropbox/Columbia SIPA/24FALL/Computing in Context/Project1/Pregnancy-Associated_Mortality_20241108.csv'

In [50]:
with open(file_path, newline='', encoding='utf-8') as csvfile:
    reader = csv.DictReader(csvfile)
    for row in reader:
        if row['Deaths']:  
            deaths_list.append(float(row['Deaths']))

mean_deaths_std = sum(deaths_list) / len(deaths_list) #sum of row /length of row = mean

sorted_deaths_list = sorted(deaths_list)

n = len(sorted_deaths_list)

if n % 2 == 0:
    median_deaths_std = (sorted_deaths_list[n // 2 - 1] + sorted_deaths_list[n // 2]) / 2 #if number in list is even, caliculate the mean of the 2 number on the center
else:
    median_deaths_std = sorted_deaths_list[n // 2] #if number in list is odd, pick the number on the center

frequency_dict = {}
for value in deaths_list:
    if value in frequency_dict:
        frequency_dict[value] += 1
    else:
        frequency_dict[value] = 1

max_count = max(frequency_dict.values()) #looking for 
mode_deaths_std = [key for key, count in frequency_dict.items() if count == max_count][0]

print("Mean:", mean_deaths_std)
print("Median:", median_deaths_std)
print("Mode:", mode_deaths_std)

Mean: 5.017021276595744
Median: 3.0
Mode: 1.0

In [54]:
sorted_counts = sorted(frequency_dict.items()) #sorting results

print("Distribution of Deaths:") #data visualization
for value, count in sorted_counts:
    bar = '█' * (count // 2) 
    print(f"{value}: {bar}")

Distribution of Deaths:
0.0: ██████
1.0: ██████████████████████████████████████████████████████████████████████████████████████████████████████████
2.0: ██████████████████████████████████████████████████████████████████████
3.0: ████████████████████████████████████████████████████████████████
4.0: ████████████████████████████████████████
5.0: ██████████████████████████████████████
6.0: ████████████████████████████
7.0: ████████████████
8.0: ██████████████████
9.0: ████████████
10.0: ██████████████
11.0: ██████████
12.0: ████████
13.0: ████████
14.0: ████
15.0: ████████
16.0: ████
20.0: ██████
21.0: ████
23.0: ████
26.0: ██